version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metabase
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    ports:
      - 5431:5432

  metabase-app:
    image: metabase/metabase
    restart: always
    ports:
      - 3001:3000
    volumes:
      - ./metabase_data:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: postgres
      MB_DB_HOST: postgres
    depends_on:
      - postgres