version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: capim
      POSTGRES_PASSWORD: capim
      POSTGRES_DB: postgres
      TZ: America/Sao_Paulo
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    ports:
      - 5433:5432